- name: Create services for WSO2 products
  template:
    src: "service.j2"
    dest: "{{ services_dir }}/wso2.{{ item.id }}.service.sh"
    mode: 0777
  with_items:
    - {name: 'WSO2 Identity Server (IS)', id: 'is', script: "{{ is_home }}/bin/wso2server.sh", portOffset: "-DportOffset=5 "}
    - {name: 'WSO2 Enterprise Integrator (EI)', id: 'ei', script: "{{ ei_home }}/bin/integrator.sh", portOffset: ""}
    - {name: 'WSO2 API Management (AM)', id: 'am', script: "{{ am_home }}/bin/wso2server.sh", portOffset: "-DportOffset=4 "}
    - {name: 'WSO2 Business Process Server (BPS)', id: 'bps', script: "{{ ei_home }}/wso2/business-process/bin/wso2server.sh", portOffset: ""}
    - {name: 'WSO2 Analystic Server (AS)', id: 'analystic', script: "{{ ei_home }}/wso2/analytics/bin/wso2server.sh", portOffset: ""}
    - {name: 'WSO2 Message Broker', id: 'message-broker', script: "{{ ei_home }}/wso2/broker/bin/wso2server.sh", portOffset: ""}

- name: Create symbolic link 
  file:
    src: "{{ services_dir }}/wso2.{{ item.id }}.service.sh"
    dest: "/etc/init.d/wso2-{{ item.id }}"
    state: link
  with_items:
    - { id: 'is' }
    - { id: 'ei' }
    - { id: 'am' }
    - { id: 'bps' }
    - { id: 'analystic' }
    - { id: 'message-broker' }